import type { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  paragraph: 'mb-1',
  heading: {
    h1: 'text-2xl font-bold mb-2',
    h2: 'text-xl font-bold mb-2',
    h3: 'text-lg font-semibold mb-1',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
  },
  list: {
    ul: 'list-disc ml-4 mb-2',
    ol: 'list-decimal ml-4 mb-2',
    listitem: 'mb-0.5',
    nested: {
      listitem: 'list-none',
    },
  },
  code: 'block bg-gray-900 text-gray-100 font-mono text-sm p-4 rounded my-2 overflow-x-auto whitespace-pre',
  codeHighlight: {
    atrule: 'text-purple-300',
    attr: 'text-yellow-300',
    boolean: 'text-orange-300',
    builtin: 'text-cyan-300',
    cdata: 'text-gray-400',
    char: 'text-green-300',
    class: 'text-cyan-300',
    'class-name': 'text-cyan-300',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-300',
    deleted: 'text-red-400',
    doctype: 'text-gray-400',
    entity: 'text-yellow-300',
    function: 'text-yellow-300',
    important: 'text-red-300',
    inserted: 'text-green-300',
    keyword: 'text-purple-300 font-semibold',
    namespace: 'text-gray-300',
    number: 'text-orange-300',
    operator: 'text-gray-300',
    prolog: 'text-gray-400',
    property: 'text-blue-300',
    punctuation: 'text-gray-400',
    regex: 'text-red-300',
    selector: 'text-green-300',
    string: 'text-green-300',
    symbol: 'text-orange-300',
    tag: 'text-red-300',
    url: 'text-blue-300',
    variable: 'text-red-200',
  },
}
